# Generated by Django 5.1.3 on 2024-11-30 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table1',
            old_name='yob',
            new_name='datetime',
        ),
    ]
