# Generated by Django 5.1.3 on 2024-11-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0002_rename_yob_table1_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='table1',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
