# Generated by Django 5.1.3 on 2024-12-02 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0004_contact2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table1',
            old_name='datetime',
            new_name='date',
        ),
    ]
