# Generated by Django 5.1.3 on 2024-12-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0005_rename_datetime_table1_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact2',
            name='subject',
            field=models.TextField(max_length=100),
        ),
    ]
